// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutMeDocumentDataSlicesSlice = never;

/**
 * Content for About me documents
 */
interface AboutMeDocumentData {
  /**
   * text field in *About me*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Slice Zone field in *About me*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutMeDocumentDataSlicesSlice> /**
   * Meta Title field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_me.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_me.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About me*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About me document from Prismic
 *
 * - **API ID**: `about_me`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutMeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutMeDocumentData>,
    "about_me",
    Lang
  >;

type ClientFeedbackItemDocumentDataSlicesSlice = never;

/**
 * Content for Client Feedback Item documents
 */
interface ClientFeedbackItemDocumentData {
  /**
   * Title field in *Client Feedback Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Client Feedback Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Feedback text field in *Client Feedback Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.feedback_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feedback_text: prismic.RichTextField;

  /**
   * photo field in *Client Feedback Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Releated Work field in *Client Feedback Item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.releated_work
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  releated_work: prismic.ContentRelationshipField;

  /**
   * Slice Zone field in *Client Feedback Item*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientFeedbackItemDocumentDataSlicesSlice> /**
   * Meta Title field in *Client Feedback Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: client_feedback_item.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Client Feedback Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: client_feedback_item.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Client Feedback Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_item.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Client Feedback Item document from Prismic
 *
 * - **API ID**: `client_feedback_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientFeedbackItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClientFeedbackItemDocumentData>,
    "client_feedback_item",
    Lang
  >;

/**
 * Item in *client feedback PAGE → feedback items*
 */
export interface ClientFeedbackPageDocumentDataFeedbackItemsItem {
  /**
   * client feedback item field in *client feedback PAGE → feedback items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_page.feedback_items[].client_feedback_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  client_feedback_item: prismic.ContentRelationshipField<"client_feedback_item">;
}

type ClientFeedbackPageDocumentDataSlicesSlice = never;

/**
 * Content for client feedback PAGE documents
 */
interface ClientFeedbackPageDocumentData {
  /**
   * feedback items field in *client feedback PAGE*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_page.feedback_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feedback_items: prismic.GroupField<
    Simplify<ClientFeedbackPageDocumentDataFeedbackItemsItem>
  >;

  /**
   * Slice Zone field in *client feedback PAGE*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientFeedbackPageDocumentDataSlicesSlice> /**
   * Meta Title field in *client feedback PAGE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: client_feedback_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *client feedback PAGE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: client_feedback_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *client feedback PAGE*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_feedback_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * client feedback PAGE document from Prismic
 *
 * - **API ID**: `client_feedback_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientFeedbackPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientFeedbackPageDocumentData>,
    "client_feedback_page",
    Lang
  >;

/**
 * Content for content type documents
 */
interface ContentTypeDocumentData {
  /**
   * Type name field in *content type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_type.type_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type_name: prismic.KeyTextField;
}

/**
 * content type document from Prismic
 *
 * - **API ID**: `content_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentTypeDocumentData>,
    "content_type",
    Lang
  >;

type HomeDocumentDataSlicesSlice = WorkTypeBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MusicItemDocumentDataSlicesSlice = never;

/**
 * Content for Music item documents
 */
interface MusicItemDocumentData {
  /**
   * Title field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *Music item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"content_type">;

  /**
   * link field in *Music item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * description field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Release Date field in *Music item*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * Slice Zone field in *Music item*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MusicItemDocumentDataSlicesSlice> /**
   * Meta Title field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: music_item.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: music_item.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Music item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Music item document from Prismic
 *
 * - **API ID**: `music_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MusicItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MusicItemDocumentData>,
    "music_item",
    Lang
  >;

/**
 * Item in *no place for fear PAGE → links to music*
 */
export interface NoPlaceForFearPageDocumentDataLinksToMusicItem {
  /**
   * link title field in *no place for fear PAGE → links to music*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: no_place_for_fear_page.links_to_music[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * link item field in *no place for fear PAGE → links to music*
   *
   * - **Field Type**: Link
   * - **Placeholder**: El link a la musiqueta
   * - **API ID Path**: no_place_for_fear_page.links_to_music[].link_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_item: prismic.LinkField;
}

type NoPlaceForFearPageDocumentDataSlicesSlice = never;

/**
 * Content for no place for fear PAGE documents
 */
interface NoPlaceForFearPageDocumentData {
  /**
   * links to music field in *no place for fear PAGE*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: no_place_for_fear_page.links_to_music[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_to_music: prismic.GroupField<
    Simplify<NoPlaceForFearPageDocumentDataLinksToMusicItem>
  >;

  /**
   * Slice Zone field in *no place for fear PAGE*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: no_place_for_fear_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NoPlaceForFearPageDocumentDataSlicesSlice> /**
   * Meta Title field in *no place for fear PAGE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: no_place_for_fear_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *no place for fear PAGE*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: no_place_for_fear_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *no place for fear PAGE*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: no_place_for_fear_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * no place for fear PAGE document from Prismic
 *
 * - **API ID**: `no_place_for_fear_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoPlaceForFearPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NoPlaceForFearPageDocumentData>,
    "no_place_for_fear_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutMeDocument
  | ClientFeedbackItemDocument
  | ClientFeedbackPageDocument
  | ContentTypeDocument
  | HomeDocument
  | MusicItemDocument
  | NoPlaceForFearPageDocument;

/**
 * Item in *WorkTypeBlock → Default → Primary → music items*
 */
export interface WorkTypeBlockSliceDefaultPrimaryMusicItemsItem {
  /**
   * music item field in *WorkTypeBlock → Default → Primary → music items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.music_items[].music_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  music_item: prismic.ContentRelationshipField<"music_item">;
}

/**
 * Primary content in *WorkTypeBlock → Default → Primary*
 */
export interface WorkTypeBlockSliceDefaultPrimary {
  /**
   * type field in *WorkTypeBlock → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"content_type">;

  /**
   * music items field in *WorkTypeBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.music_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  music_items: prismic.GroupField<
    Simplify<WorkTypeBlockSliceDefaultPrimaryMusicItemsItem>
  >;
}

/**
 * Default variation for WorkTypeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkTypeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkTypeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkTypeBlock*
 */
type WorkTypeBlockSliceVariation = WorkTypeBlockSliceDefault;

/**
 * WorkTypeBlock Shared Slice
 *
 * - **API ID**: `work_type_block`
 * - **Description**: WorkTypeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkTypeBlockSlice = prismic.SharedSlice<
  "work_type_block",
  WorkTypeBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutMeDocument,
      AboutMeDocumentData,
      AboutMeDocumentDataSlicesSlice,
      ClientFeedbackItemDocument,
      ClientFeedbackItemDocumentData,
      ClientFeedbackItemDocumentDataSlicesSlice,
      ClientFeedbackPageDocument,
      ClientFeedbackPageDocumentData,
      ClientFeedbackPageDocumentDataFeedbackItemsItem,
      ClientFeedbackPageDocumentDataSlicesSlice,
      ContentTypeDocument,
      ContentTypeDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MusicItemDocument,
      MusicItemDocumentData,
      MusicItemDocumentDataSlicesSlice,
      NoPlaceForFearPageDocument,
      NoPlaceForFearPageDocumentData,
      NoPlaceForFearPageDocumentDataLinksToMusicItem,
      NoPlaceForFearPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      WorkTypeBlockSlice,
      WorkTypeBlockSliceDefaultPrimaryMusicItemsItem,
      WorkTypeBlockSliceDefaultPrimary,
      WorkTypeBlockSliceVariation,
      WorkTypeBlockSliceDefault,
    };
  }
}
