// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutMeDocumentDataSlicesSlice = never;

/**
 * Content for About me documents
 */
interface AboutMeDocumentData {
  /**
   * text field in *About me*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Slice Zone field in *About me*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutMeDocumentDataSlicesSlice> /**
   * Meta Title field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_me.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_me.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About me*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About me document from Prismic
 *
 * - **API ID**: `about_me`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutMeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutMeDocumentData>,
    "about_me",
    Lang
  >;

/**
 * Content for content type documents
 */
interface ContentTypeDocumentData {
  /**
   * Type name field in *content type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_type.type_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type_name: prismic.KeyTextField;
}

/**
 * content type document from Prismic
 *
 * - **API ID**: `content_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentTypeDocumentData>,
    "content_type",
    Lang
  >;

type HomeDocumentDataSlicesSlice = WorkTypeBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MusicItemDocumentDataSlicesSlice = never;

/**
 * Content for Music item documents
 */
interface MusicItemDocumentData {
  /**
   * Title field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *Music item*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"content_type">;

  /**
   * link field in *Music item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * description field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Music item*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MusicItemDocumentDataSlicesSlice> /**
   * Meta Title field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: music_item.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Music item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: music_item.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Music item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: music_item.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Music item document from Prismic
 *
 * - **API ID**: `music_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MusicItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MusicItemDocumentData>,
    "music_item",
    Lang
  >;

export type AllDocumentTypes =
  | AboutMeDocument
  | ContentTypeDocument
  | HomeDocument
  | MusicItemDocument;

/**
 * Item in *WorkTypeBlock → Default → Primary → music items*
 */
export interface WorkTypeBlockSliceDefaultPrimaryMusicItemsItem {
  /**
   * music item field in *WorkTypeBlock → Default → Primary → music items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.music_items[].music_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  music_item: prismic.ContentRelationshipField<"music_item">;
}

/**
 * Primary content in *WorkTypeBlock → Default → Primary*
 */
export interface WorkTypeBlockSliceDefaultPrimary {
  /**
   * type field in *WorkTypeBlock → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"content_type">;

  /**
   * music items field in *WorkTypeBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_type_block.default.primary.music_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  music_items: prismic.GroupField<
    Simplify<WorkTypeBlockSliceDefaultPrimaryMusicItemsItem>
  >;
}

/**
 * Default variation for WorkTypeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkTypeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkTypeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkTypeBlock*
 */
type WorkTypeBlockSliceVariation = WorkTypeBlockSliceDefault;

/**
 * WorkTypeBlock Shared Slice
 *
 * - **API ID**: `work_type_block`
 * - **Description**: WorkTypeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkTypeBlockSlice = prismic.SharedSlice<
  "work_type_block",
  WorkTypeBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutMeDocument,
      AboutMeDocumentData,
      AboutMeDocumentDataSlicesSlice,
      ContentTypeDocument,
      ContentTypeDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MusicItemDocument,
      MusicItemDocumentData,
      MusicItemDocumentDataSlicesSlice,
      AllDocumentTypes,
      WorkTypeBlockSlice,
      WorkTypeBlockSliceDefaultPrimaryMusicItemsItem,
      WorkTypeBlockSliceDefaultPrimary,
      WorkTypeBlockSliceVariation,
      WorkTypeBlockSliceDefault,
    };
  }
}
